[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "1.1.*"

[profile.release]
debug = true
painc = "abort"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "AoC"
harness = false
